import React from 'react';
import Terms  from "../Assets/Terms.jpeg";
 


const TermsAndConditions = () => {
  return (
    <div style={styles.card}>
    <div style={styles.container}>
      <div style={styles.container}>
      <img src={Terms} alt="Terms and Conditions" style={styles.image} />
      </div>
      <h1 style={styles.header}>PRO GO Fantasy Terms and Conditions</h1>
      <p style={styles.intro}>
        This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines and Digital Media Ethics Code) Rules, 2021 that require publishing the rules and regulations, privacy policy and user agreement for access or usage of our website ‘www.progofantasy.shop’ (hereinafter referred to as the “Website”, “Mobile Application”, or “Platform”). PRO GO Fantasy Fantasy Sports Private Limited is incorporated under the Companies Act, 2013 having its registered office at Accelerator Coworking Space, Ground Floor, MGF Metropolis Mall, Mehrauli-Gurgaon Rd, Gurugram, Haryana 122002 (hereinafter, referred to as “we”, “us”, “our” and “PRO GO Fantasy”).
      </p>
      <p style={styles.section}>
        This document is an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
      </p>
      <p style={styles.section}>
        For the purpose of these Terms and Conditions (defined hereinafter), “you”, “your” or “User” refers to any natural or legal person (whether a registered user or otherwise) who accesses the Website, its contents and uses the services offered by PRO GO Fantasy on or through the Website.
      </p>
      <p style={styles.section}>
        Your use of our Website and its related sites, services and tools is governed by these Terms and Conditions contained in this agreement that applies to the Website (“User Terms”). By using the Website, you have impliedly agreed to and accepted these User Terms. If you do not agree or are not willing to be bound by the terms and conditions of these User Terms (and the rules and policies displayed on the Website), please do not click on the REGISTER/LOGIN, SUBSCRIBE NOW or any other related buttons and do not seek to obtain access to or otherwise use the Website. As long as you comply with the provisions of these User Terms, we grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy is not affiliated with any private or government sports leagues or tournaments unless explicitly stated. Additionally, PRO GO Fantasy does not have any official association with any sports teams or individuals.
      </p>
      <p style={styles.section}>
        The term “PRO GO Fantasy” used in these Terms and Conditions, refers to both the PRO GO Fantasy Website and Mobile Application on Android Play Store and iOS App Store.
      </p>

      <h2 style={styles.subHeader}>1. Intellectual Property</h2>
      <p style={styles.section}>
        You may download or copy Content only to the extent such download is expressly permitted in writing on the Website. No right, title or interest in any downloaded materials or software is transferred to you as a result of any such downloading or copying. You may not reproduce (except as noted above), publish, transmit, distribute, display, modify, create derivative works from, sell or participate in any sale of or exploit in any way, in whole or in part, any of the Content, the Website or any related software.
      </p>
      <p style={styles.section}>
        Nothing on the Website will be interpreted as granting any license or right to use any image, trademark, logo or service mark on the Website. Anything transmitted to the Website by you becomes PRO GO Fantasy’s property and may be used by us for any lawful purpose. PRO GO Fantasy reserves all rights with respect to copyright and trademark ownership of all material on the Website, and will enforce such rights to the full extent of the law.
      </p>
      <p style={styles.section}>
        Unless otherwise noted, all Contents are copyrights, trademarks and/or other intellectual property owned, controlled or licensed by PRO GO Fantasy or by third parties who have licensed their materials to PRO GO Fantasy and are protected by Indian and international copyright laws. The compilation of all Contents on the Website is the exclusive property of PRO GO Fantasy and is also protected by Indian and international copyright laws.
      </p>
      <p style={styles.section}>
        The Website, including all Information, is owned by or licensed to PRO GO Fantasy and is subject to and protected by various intellectual property rights, including but not limited to the copyright, trade secrets, trademarks, service marks, brand names and other proprietary rights whether under contract, statute or any similar provisions ( “IP Rights” ). All IP Rights are and will remain the exclusive property of PRO GO Fantasy, its respective third-party licensors or third parties to whom it is attributed and in using the Website, individual Users will not obtain any rights, title or other interest in or to any information on the Website or related IP Rights.
      </p>
      <p style={styles.section}>
        Subject to the above, individual Users are entitled to view the Information on the Website and to copy and print such information for personal use. Individual Users are not permitted to sell or distribute or otherwise deal with the Information on the Website or any deviations of such information without the prior written consent of PRO GO Fantasy. The Website uses different web analytics services and is compliant with its Terms and Conditions.
      </p>
      <p style={styles.section}>
        By accepting the T&Cs, the User grants PRO GO Fantasy and its affiliates, partners, licensors, and associates a worldwide, irrevocable, royalty-free, non-exclusive, sublicensable licence to use, reproduce, create derivative works, distribute, publicly perform, publicly display, transfer, transmit and/or publish their User’s Content for the following purposes:
        <ul style={styles.list}>
          <li>Displaying User’s Content on PRO GO Fantasy;</li>
          <li>Distributing User’s Content to other users, electronically or through other media;</li>
          <li>Storing User’s Content in a remote database accessible by end users, for a charge;</li>
          <li>This licence applies to the distribution and storage of the User’s Content in any form, medium or technology.</li>
        </ul>
      </p>
      <p style={styles.section}>
        Permission to modify, publish, transmit, sell, reproduce, create derivative works or publicly display any content on www.progofantasy.shop can be requested at info@progofantasy.shop.
      </p>
      <p style={styles.section}>
        The User is solely responsible for any material it uploads, posts, emails, transmits or make available on PRO GO Fantasy ( “User’s Content” ). The User ensures that it holds the intellectual property rights in their User’s Content and that it does not infringe any third-party rights. User also agrees not to use or display any names, logos, marks, labels, trademarks, copyrights or intellectual property rights of any third party on PRO GO Fantasy. User accepts and agrees that PRO GO Fantasy and its directors, employees, affiliates, and assigns will not be liable for any costs, damages, loss or harm, including litigation costs and counsel fees, arising from any claims by a third party resulting from the display or use of any names, logos, marks, labels, trademarks, copyrights or intellectual property rights on PRO GO Fantasy through the User’s omissions.
      </p>
      <p style={styles.section}>
        The User consents to receive communications, such as announcements, administrative messages and advertisements, from PRO GO Fantasy or any of its partners, licensors or associates.
      </p>

      <h2 style={styles.subHeader}>2. Usage of Website and Mobile Application</h2>
      <p style={styles.section}>
        Users using the services offered by www.progofantasy.shop or the PRO GO Fantasy App, including Features, by participating in various contests and games organised on the platform (“Contests”) are bound to follow these Terms and Conditions, and all other rules and regulations defined by PRO GO Fantasy.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy reserves the right to modify or change these Terms and Conditions, rules and regulations at any time by posting them on www.progofantasy.shop. By using PRO GO Fantasy services, Users agree to time-to-time amendments that may be made. Users will be informed of any amendments via email to their registered address or by posting notifications in their accounts. If a User disagrees or does not accept the amendments, they can indicate their non-acceptance within the defined time frame. If a user fails to do so, they will be deemed to have accepted the changes. In case of non-acceptance, PRO GO Fantasy reserves the right to restrict the User from using its services and features.
      </p>
      <p style={styles.section}>
        Additional rules and regulations may apply to the various services offered as part of the features. If there are additional conditions that conflict with these Terms and Conditions, the additional conditions will take precedence.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy offers several interactive functionalities on the App to enhance the user experience. These functionalities are referred to as “features” in all the sections of these Terms and Conditions.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy may, at its discretion:
        <ul style={styles.list}>
          <li>Restrict, suspend or terminate a User’s access to all or part of www.progofantasy.shop or features of PRO GO Fantasy.</li>
          <li>Change, suspend or discontinue all or part of the features.</li>
          <li>Deactivate or delete a User’s account and related information and files.</li>
          <li>Reject, move or remove any material submitted by a User.</li>
          <li>Move or remove any content available on www.progofantasy.shop and PRO GO Fantasy application.</li>
          <li>Establish general practices and limits for the use of www.progofantasy.shop and PRO GO Fantasy application.</li>
          <li>Revise or add to the roster of players for selection in a Contest.</li>
          <li>Assign its rights and liabilities to another entity (after informing users via registered email).</li>
        </ul>
      </p>
      <p style={styles.section}>
        PRO GO Fantasy reserves the right to restrict, suspend, or terminate a user’s access, deactivate or delete their account and delete their content without notice if they breach these Terms and Conditions or use PRO GO Fantasy services or features illegally or inappropriately. PRO GO Fantasy may also take technical or legal action against such a user.
      </p>
      <p style={styles.section}>
        In case of suspension or deletion due to PRO GO Fantasy negligence, PRO GO Fantasy will repay the platform fee charged for any features. No refund will be made in case of suspension or removal due to:
        <ul style={styles.list}>
          <li>Breach of these Terms and Conditions or inappropriate use of PRO GO Fantasy.</li>
          <li>Circumstances beyond PRO GO Fantasy’s reasonable control.</li>
        </ul>
      </p>
      <p style={styles.section}>
        By accepting these Terms and Conditions, Users agree to receive communications, including announcements, administrative messages and advertisements, from PRO GO Fantasy or its partners, licensors or associates.
      </p>

      <h2 style={styles.subHeader}>3. Third Party Sites, Services, and Products</h2>
      <p style={styles.section}>
        PRO GO Fantasy platform may contain links to third-party sites, services and products that are owned and operated by independent entities. These third-party sites may have different terms of use for users. PRO GO Fantasy does not have control over or assume any responsibility for the content or practices of these third-party sites. The inclusion of links to third-party sites on PRO GO Fantasy does not imply endorsement of such sites or any affiliation with their operators.
      </p>
      <p style={styles.section}>
        Users transact with third parties, including payment providers and verification service providers, at their own risk. Users are solely responsible for reviewing the policies, terms and conditions of these third parties before conducting any transactions or availing of any services. By accepting the Terms and Conditions of PRO GO Fantasy, users agree that PRO GO Fantasy is not responsible for any damages or losses incurred as a result of any transactions, correspondence or related activities with third parties. Any questions, complaints or claims regarding third-party products or services should be directed to the relevant vendor.
      </p>
      <p style={styles.section}>
        www.progofantasy.shop and PRO GO Fantasy application features content created and posted by both PRO GO Fantasy and various third parties. PRO GO Fantasy does not guarantee the accuracy, integrity or quality of the content created by third parties and such content should not be relied upon by users in connection with the use of the features provided by PRO GO Fantasy or participation in any contests hosted on the platform.
      </p>

      <h2 style={styles.subHeader}>4. Privacy Policy</h2>
      <p style={styles.section}>
        PRO GO Fantasy collects user information, including personal details and payment information, at the time of registration. This information is subject to PRO GO Fantasy’s Privacy Policy, which can be reviewed by users on the Privacy Policy page.
      </p>

      <h2 style={styles.subHeader}>5. User Conduct</h2>
      <p style={styles.section}>
        The terms and conditions, rules, regulations and terms of use established by PRO GO Fantasy are binding on all users and must be strictly adhered to. If a user fails to comply with these terms, PRO GO Fantasy reserves the right to take action against the user, which may include but is not limited to:
        <ul style={styles.list}>
          <li>Restricting, suspending, or terminating a user’s access to all or any part of PRO GO Fantasy’s features;</li>
          <li>Deactivating or deleting a User’s account and all related information and files; or</li>
          <li>Refraining from awarding any winnings to the User.</li>
        </ul>
      </p>
      <p style={styles.section}>
        By accepting the Terms and Conditions of PRO GO Fantasy, Users agree to provide accurate, current and complete information during the registration process and at other times as required by PRO GO Fantasy. Users also agree to keep their registration information up-to-date.
      </p>
      <p style={styles.section}>
        Each User is allowed to register and operate only one account with PRO GO Fantasy, whether on the website or the app.
      </p>
      <p style={styles.section}>
        Users consent to receive all communications from PRO GO Fantasy by marking PRO GO Fantasy emails as “safe senders.” If a user does not receive PRO GO Fantasy emails due to them being sent to the spam or junk folder, PRO GO Fantasy will not be held responsible.
      </p>
      <p style={styles.section}>
        Any password issued by PRO GO Fantasy to a User is confidential and must not be shared with anyone else. Users are solely responsible for maintaining the confidentiality of their accounts and passwords and agree to immediately notify PRO GO Fantasy of any unauthorized use of their passwords or accounts or any other security breach.
      </p>
      <p style={styles.section}>
        Users are solely responsible for the security and confidentiality of any payment accounts linked to their PRO GO Fantasy account. In case of any misuse of the linked payment accounts, PRO GO Fantasy will not be liable and such misuse must be reported to PRO GO Fantasy immediately.
      </p>
      <p style={styles.section}>
        Users agree to log out of their accounts after the completion of each session. In the event of any loss or damage resulting from the failure to do so, PRO GO Fantasy will not be held responsible.
      </p>
      <p style={styles.section}>
        Users agree not to engage in or assist in the use of cheats, exploits, automation, software, bots, hacks, or any unauthorized third-party software designed to modify or interfere with PRO GO Fantasy’s features and/or experience.
      </p>
      <p style={styles.section}>
        Users agree not to copy or modify the technology and software associated with PRO GO Fantasy and its features, nor to rent, loan, sell, assign, distribute, reverse engineer, grant a security interest in or otherwise transfer any rights to any of the associated technologies and software.
      </p>
      <p style={styles.section}>
        Users agree not to modify or cause the modification of any files, technology or software associated with PRO GO Fantasy.
      </p>
      <p style={styles.section}>
        Users agree not to disrupt or overburden the servers or computers supporting PRO GO Fantasy’s services or the enjoyment of PRO GO Fantasy features by other users or persons.
      </p>
      <p style={styles.section}>
        Users agree not to access PRO GO Fantasy’s User accounts, servers, or networks associated with PRO GO Fantasy’s features by any means other than the user interface provided by PRO GO Fantasy. Users also agree not to engage in activities designed to circumvent or modify any security, technology, device or software associated with PRO GO Fantasy’s features.
      </p>
      <p style={styles.section}>
        Users agree not to use the PRO GO Fantasy platform for any illegal or inappropriate activities, including, but not limited to:
        <ul style={styles.list}>
          <li>Any action or communication that is obscene, offensive, indecent, racial, communal, anti-national, objectionable, defamatory or abusive;</li>
          <li>Harassment, stalking, threatening or otherwise violating the legal rights of others;</li>
          <li>Transmitting files that contain viruses, corrupted files, or any other software or programs that may cause damage or negatively impact the operation of another person’s computer, www.progofantasy.shop, PRO GO Fantasy application or any software, hardware or telecommunications equipment;</li>
          <li>Advertising, offering or selling any goods or services for commercial purposes without the express written consent of PRO GO Fantasy;</li>
          <li>Transmitting content related to services, products, surveys, contests, pyramid schemes, spam, unsolicited advertising or promotional materials, or chain letters.</li>
        </ul>
      </p>
      <p style={styles.section}>
        The User shall not engage in or support any sort of attack on PRO GO Fantasy, including but not limited to the distribution of a virus, denial of service or other attempts to interrupt the services provided by PRO GO Fantasy or the use or enjoyment of other PRO GO Fantasy users.
      </p>

      <h2 style={styles.subHeader}>6. Registration</h2>
      <p style={styles.section}>
        To sign up for an account on PRO GO Fantasy, Users must provide their mobile number, which will receive a One-Time Password (OTP) for verification. Additionally, they can enter a referral code to receive a ₹25 Cash Bonus.
      </p>
      <p style={styles.section}>
        Users can also sign-up using Truecaller if they have a Truecaller account and app installed on their phone.
      </p>
      <p style={styles.section}>
        Once the User receives the OTP, they must enter it to complete the registration process and log in to their account. To participate in contests, Users must provide accurate information such as their date of birth and the pin code of their residence. The information provided for verification must match the information on their required documents.
      </p>
      <p style={styles.section}>
        Before using any of the features provided by PRO GO Fantasy, participants must acknowledge that they have read and understood the Terms and Conditions and will comply with all the rules, regulations, and terms of use.
      </p>
      <p style={styles.section}>
        Certain states in India have implemented limitations on fantasy sports and real money gaming platforms and are designated as restricted states. Residents of Assam, Odisha, Telangana, Nagaland, Sikkim and Andhra Pradesh cannot participate in pay-to-play contests for fantasy sports. If a User accessing the services of PRO GO Fantasy is found to be a resident of any of these restricted states, they will be entirely liable for any legal or penal consequences. PRO GO Fantasy reserves the right to delete or deactivate their account and forfeit any remaining balance in their account.
      </p>
      <p style={styles.section}>
        Furthermore, residents of Andhra Pradesh, Assam, Nagaland, Odisha, Sikkim and Telangana cannot use the Rummy game on the PRO GO Fantasy application. Finally, residents of these states (excluding Gujarat and Tamil Nadu) cannot use skill-based games on the PRO GO Fantasy application.
      </p>
      <h3 style={styles.subSubHeader}>Banned States</h3>
      <table style={styles.table}>
        <thead>
          <tr>
            <th>State</th>
            <th>Fantasy Sports</th>
            <th>Rummy</th>
            <th>Poker</th>
            <th>Skill-Based Games</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Andhra Pradesh</td>
            <td>False</td>
            <td>False</td>
            <td>False</td>
            <td>False</td>
          </tr>
          <tr>
            <td>Assam</td>
            <td>False</td>
            <td>False</td>
            <td>False</td>
            <td>False</td>
          </tr>
          <tr>
            <td>Nagaland</td>
            <td>False</td>
            <td>False</td>
            <td>False</td>
            <td>False</td>
          </tr>
          <tr>
            <td>Odisha</td>
            <td>False</td>
            <td>False</td>
            <td>False</td>
            <td>False</td>
          </tr>
          <tr>
            <td>Sikkim</td>
            <td>False</td>
            <td>False</td>
            <td>False</td>
            <td>False</td>
          </tr>
          <tr>
            <td>Telangana</td>
            <td>False</td>
            <td>False</td>
            <td>False</td>
            <td>False</td>
          </tr>
          <tr>
            <td>Gujarat</td>
            <td>True</td>
            <td>True</td>
            <td>False</td>
            <td>True</td>
          </tr>
          <tr>
            <td>Tamil Nadu</td>
            <td>True</td>
            <td>True</td>
            <td>True</td>
            <td>True</td>
          </tr>
        </tbody>
      </table>

      <h2 style={styles.subHeader}>7. Contests, Participation, and Prizes</h2>
      <p style={styles.section}>
        The PRO GO Fantasy platform conducts various contests as part of the features offered by PRO GO Fantasy. These contests include fantasy cricket, football, kabaddi, volleyball, basketball, handball, hockey, baseball, rugby and US football. Participants in the contests create fantasy teams consisting of on-field players from the relevant match, series or tournament. Points are awarded based on the performance of these players and the user with the highest aggregate of points is declared winner of the contest. PRO GO Fantasy may declare more than one winner and distribute winnings accordingly in increasing order of their teams’ scores. The contests comply with the “Fantasy Rules” and other terms, conditions and regulations mentioned in the “How To Play” section.
      </p>
      <p style={styles.section}>
        Users may participate in paid versions of the contests by paying a pre-defined entry fee, as stated on the relevant contest page. An individual is authorized to create multiple teams for participating in contests unless otherwise specified. In the case of multiple-entry contests, users may submit more than one team but are not allowed to edit their teams after the match deadline is closed. PRO GO Fantasy may limit the number of multiple teams allowed in a contest or the number of teams a single user account can create.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy is authorized to charge a predefined entry fee for accessing the features. However, residents of restricted states are not allowed to participate in paid versions of the contests.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy offers three variations in contests:
        <ul style={styles.list}>
          <li><strong>Guaranteed Contests:</strong> As the name suggests, guaranteed contests offer guaranteed winnings and will not get cancelled, even if they do not meet the participant requirements/spots.</li>
          <li><strong>Flexible Contests:</strong> In flexible contests, there should be at least 3 users and a maximum of 100 users in the contest. If there are two users in the flexible contest, the respective contest will be converted into head-to-head. The flexible contests will get cancelled, if the contest receives less than 50% participation. For instance, if a flexible contest has a total of 20 spots and 8 users join the contest, this contest will be cancelled. For this flexible contest to carry on, a minimum of 10 users are required to join.</li>
          <li><strong>Guaranteed + Flexible Contests:</strong> Users will also find flexible + guaranteed contests. In these contests, league price and winning is varied depending on the number of users joining the contest. This contest will not get cancelled, irrespective of number of users joining the contest.</li>
        </ul>
      </p>
      <p style={styles.section}>
        Please note that the league price and winning distribution of flexible contests and Guaranteed + Flexible Contests will change once the match is live.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy holds the right to abandon a contest, adjust its deadline, or change the deadline in unavoidable circumstances beyond its control. The platform can adjust the deadline by 10 minutes or 3 overs (whichever is less) before the official match start time for cricket and by a maximum of 10 minutes for other sports. If PRO GO Fantasy is unable to cross-check the official match start time, it may adjust its deadline such that a maximum of 3 overs are bowled in the adjusted time. In the case of the official match start time being after PRO GO Fantasy’s deadline, the platform may abandon, cancel or delay the start of the contest by extending the deadline in certain unavoidable circumstances, such as weather conditions, technical glitches, non-appearance of teams, natural disasters, etc.
      </p>

      <h2 style={styles.subHeader}>8. Play Formats</h2>
      <p style={styles.section}>
        The game format offered on PRO GO Fantasy allows the Users to create their teams even after the playing team for a respective match has been announced. The Users are allowed to create or edit their teams till the last moment, i.e., right before the beginning of the real match.
      </p>
      <p style={styles.section}>
        The deadline for creating or editing teams is determined by the official start of the match, which may either be extended or shortened based on the sport being played. It is recommended that users save their teams frequently.
      </p>
      <p style={styles.section}>
        The playing team information for live matches is sourced either from official sources or our experts but does not guarantee 100% accuracy. This information may be updated at any time.
      </p>
      <p style={styles.section}>
        A green dot will be displayed next to the player’s name on the Create Team page once the playing team information has been received from official sources.
      </p>
      <p style={styles.section}>
        In the event of errors or inaccuracies in the playing team information due to the official data provider’s shortcomings, no contest entry amount will be refunded. Users are advised to cross-check playing team information on other official platforms.
      </p>
      <p style={styles.section}>
        It is possible that playing team information may not be available right before the start of the live match, but this occurs infrequently. Users are advised to be aware of this possibility.
      </p>

      <h2 style={styles.subHeader}>9. Contest Formats</h2>
      <p style={styles.section}>
        PRO GO Fantasy conducts contests as part of its features, offering both public and private contest options for Users to participate. The following Terms and Conditions apply to both public and private contests (but are not limited to):
      </p>
      <p style={styles.section}>
        <strong>Public Contest:</strong>
        <ul style={styles.list}>
          <li>PRO GO Fantasy may offer a pre-defined number of participants for the public contest format of the contest.</li>
          <li>The public contest format of the contest may be conducted as a paid contest, and the winner may be announced at the end of the contest.</li>
          <li>The minimum number of participants required to make the contest operational may be pre-defined by PRO GO Fantasy. If the required number of participants is reached, the contest will start as scheduled. If not, the contest will be cancelled and the contest entry fee will be refunded to participants without any deductions or charges.</li>
          <li>PRO GO Fantasy is solely authorized to change or alter the total winning amount and the number of winners in any flexible public contest(s) on the app. For instance, the Infinity Contest on PRO GO Fantasy is a flexible fantasy contest where the total winning amount and the number of winners are variable and can be changed at any given time, following the total number of participants in the respective contest(s). All the decisions or changes are made under the sole discretion of PRO GO Fantasy Fantasy Sports Pvt. Ltd.</li>
        </ul>
      </p>
      <p style={styles.section}>
        <strong>“Teams War” Contest:</strong>
        <ul style={styles.list}>
          <li>Points will be awarded to teams based on the performance of their individual players. The individual or team with the highest total points at the end of the match will be declared the winner.</li>
          <li>The total points you have in the contest will be calculated by adding up the points from all of your teams. If you have multiple teams, the points from each of them will be combined to give your overall total points in the contest. For instance, if you have three teams in the contest, the total points will be the sum of the points from all three teams (Team 1 + Team 2 + Team 3 = Total Points).</li>
          <li>It is a requirement to pay an entry fee for every team that you participate with. The cost of the entry fee must be paid for each individual team that is registered. Please note that failure to pay the entry fee will result in the team being unable to participate in the contest.</li>
          <li>In the scenario of a tie for any rank, the winning amount will be shared equally among the players who are tied. This applies to any situation where multiple players have the same points, score or any other measurement used to determine the winner of a certain place.</li>
          <li>PRO GO Fantasy reserves the right to modify, suspend or cancel the contest, or the terms and conditions, at any time without liability. By entering the contest, users consent to the use of their personal information in accordance with the app’s privacy policy.</li>
        </ul>
      </p>
      <p style={styles.section}>
        <strong>Private Contest:</strong>
        <ul style={styles.list}>
          <li>PRO GO Fantasy offers private contests as another form of a contest on its platform, allowing Users to create contest(s) and invite friends or other PRO GO Fantasy users to compete.</li>
          <li>Private contests are pay-to-play contests with a minimum of 2 participants and a maximum of 50 participants. The minimum winning amount can be ₹20, and the maximum winning amount can be ₹50,000. The users after creating a private contest/(s), will be given a unique identification code called the “Contest Code”, which can be shared by the users among other users to join the contest/(s).</li>
          <li>The User who creates a private contest with 10 or more players is rewarded with a percentage share of PRO GO Fantasy’s commission if the contest gets filled. The reward percentage is 15% if the contest is filled with 10-14 players and 25% if the contest is filled with 15-50 players.</li>
          <li>The total winning amount in a private contest can be distributed among multiple winners, either manually defined by the User or automatically defined by PRO GO Fantasy. The User can choose between the two options while creating a private contest.</li>
          <li>Changes to the winning amount and number of participants are not allowed once a private contest is created, except for the name of the contest.</li>
          <li>To join a private contest, the invited User must provide the contest code and pay the contest entry fee. Private contests operate on a first-come, first-served basis and once the required number of participants is reached, no additional participants will be allowed.</li>
          <li>Private contests will not be cancelled even if the required number of participants is not reached, and winnings will be automatically recalculated based on the number of joined participants.</li>
          <li>In the automatic recalculation of winnings, winnings in decimal will be rounded off to the nearest whole number. If the winning amount ends in .5, it will be rounded off to the nearest whole number.</li>
        </ul>
      </p>

      <h2 style={styles.subHeader}>10. Legality of Game of Skill</h2>
      <p style={styles.section}>
        The legality of games of skill, such as those offered on fantasy sports platforms, has been established by Indian gambling legislation and court decisions. The Public Gambling Act of 1867 does not apply to games of skill and in 2020, the Haryana High Court dismissed a Public Interest Litigation (PIL) by Ravindra Singh Chaudhary that questioned the legality of playing fantasy sports. The Court held that fantasy sports, as a game of skill where fees are paid to compete for prizes, are a legitimate business protected by Article 19(1)(g) of the Indian Constitution, which guarantees the right to engage in an occupation, trade or business.
      </p>
      <p style={styles.section}>
        The Contest/(s) offered as the features are considered games of skill as their outcome depends on the participant’s knowledge of the games of cricket, football, kabaddi, volleyball, basketball, hockey, handball, rugby, baseball, US football and players, their attention to the Contest and their ability to make strategic decisions. The success of participants depends on factors such as their knowledge of the statistics of the games, the form of the players and the conditions of the match. Participants are required to field well-balanced teams with available resources and make substitutions at appropriate times to earn maximum points.
      </p>
      <p style={styles.section}>
        By participating in these Contest/(s), each Participant acknowledges and agrees that they are participating in a game of skill.
      </p>
      <p style={styles.section}>
        More about the legality of PRO GO Fantasy can be found at the website of the All India Gaming Federation (AIGF): www.aigf.in. AIGF is the apex industry body for Online Skill Gaming in India. AIGF’s self-regulation charter for Online Skill Gaming is based on the principles of Transparency, Integrity and Responsible Gaming.
      </p>

      <h2 style={styles.subHeader}>11. Eligibility</h2>
      <p style={styles.section}>
        The Contest(s) are open to individuals who are 18 years of age or older and are currently residing in India.
      </p>
      <p style={styles.section}>
        Individuals residing in the restricted states may not participate in pay-to-play contests as the laws of these states prohibit participation in games of skill where participants are required to pay to enter.
      </p>
      <p style={styles.section}>
        Only those Participants who have successfully registered on PRO GO Fantasy application and completed the required registration procedure are eligible to participate in the Contest(s) and earn winnings.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy reserves the right to bar individuals residing in the restricted states from participating in the Contest(s).
      </p>
      <p style={styles.section}>
        If a User is found to be a resident of any of the prohibited states and is found to have concealed this fact at the time of registration, PRO GO Fantasy may take actions including but not limited to blocking, resetting, deletion or deactivation of the account.
      </p>
      <p style={styles.section}>
        If the laws of the prohibited states change and residents are allowed to participate in paid versions of the Game of Skills, these users will be treated as new registrations and previous winnings will not be considered. Any claims of this nature will not be entertained.
      </p>

      <h2 style={styles.subHeader}>12. Selection and Verification of Winners and Conditions Relating to the Winnings</h2>
      <h3 style={styles.subSubHeader}>Selection of Winners:</h3>
      <p style={styles.section}>
        PRO GO Fantasy will select the winners based on the highest aggregate score of their selected players in the designated round of the contest.
      </p>
      <p style={styles.section}>
        The number of winners and winnings to be distributed will be pre-defined by PRO GO Fantasy before the game begins.
      </p>
      <p style={styles.section}>
        Individuals who are found creating teams on behalf of other users will be disqualified.
      </p>
      <p style={styles.section}>
        In the event of a tie, the winning users will be declared as the winners and the winnings will be divided equally among such participants.
      </p>
      <p style={styles.section}>
        If the users have not complied with the terms and conditions defined by PRO GO Fantasy, they will not be eligible to receive any winnings.
      </p>
      <h3 style={styles.subSubHeader}>Contacting Winners:</h3>
      <p style={styles.section}>
        PRO GO Fantasy will contact the winners of the contest(s) through email or mobile number provided at the time of registration/verification.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy will publish the list of participants on a separate webpage and inform the winners through email.
      </p>
      <p style={styles.section}>
        If a winner’s name is displayed on the webpage but they have not received any communication, they must contact PRO GO Fantasy within the specified time.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy shall not be held responsible for any communication or omissions that might lead to a situation wherein the results may not be communicated to the Winner. Therefore, users must provide complete and accurate details at the time of registration/verification.
      </p>
      <h3 style={styles.subSubHeader}>Verification Process</h3>
      <p style={styles.section}>
        Participants must complete the verification process and submit the required documents within the specified time limit to withdraw/receive their accumulated earnings.
      </p>
      <p style={styles.section}>
        Requests for extending the time limit will not be accepted by PRO GO Fantasy.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy is authorized to disqualify any winner from withdrawing their accumulated earnings if:
        <ul style={styles.list}>
          <li>The provided document or information is inadequate, incorrect, misleading, false, fabricated, incomplete or illegible</li>
          <li>The participant does not fulfill the eligibility criteria</li>
          <li>Any other ground as determined by PRO GO Fantasy</li>
        </ul>
      </p>
      <h3 style={styles.subSubHeader}>Miscellaneous</h3>
      <p style={styles.section}>
        Winning distribution and awarding decisions made by PRO GO Fantasy are final, binding and non-contestable.
      </p>
      <p style={styles.section}>
        Participants in paid formats of the contest(s) must not be residents of restricted states.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy reserves the right to disqualify and suspend/terminate the accounts of participants who are residents of the above-mentioned states.
      </p>
      <p style={styles.section}>
        In case of a head-to-head contest with the same team and captain/vice-captain, no winner will be declared and contest entry amounts will be refunded to the respective user account.
      </p>
      <p style={styles.section}>
        A User creating or logging in multiple IDs from a single device is a fair play violation and will result in games not being visible to the respective user.
      </p>
      <h3 style={styles.subSubHeader}>Free Contest</h3>
      <p style={styles.section}>
        PRO GO Fantasy often organizes free contests, where Users can earn winnings without paying any contest entry fee.
      </p>
      <p style={styles.section}>
        The winning amount can only be used to join further pay-to-play contests organized by PRO GO Fantasy and cannot be used or withdrawn for any other purpose.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy reserves the right to forfeit the winnings of participants below the age of 18. PRO GO Fantasy will disqualify such Users and can also suspend or terminate their accounts.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy is authorized to modify or change the winnings offered to the participants declared as the winners of Contest/(s) organized by PRO GO Fantasy, and the participants not raise any claim or question the decision of PRO GO Fantasy related to the winning modification.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy makes no warranties about the quality, suitability or merchantability of the winnings and is authorized to modify or change the winnings offered.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy shall not be held responsible or liable for any damage or loss to the winnings during transportation and the customer will bear any transportation charges.
      </p>
      <p style={styles.section}>
        The winnings given to the participants are non-transferable, non-refundable and cannot be exchanged or redeemed for cash or kind.
      </p>
      <p style={styles.section}>
        Transaction charges for cash winnings will be borne by the customer.
      </p>
      <h3 style={styles.subSubHeader}>Suspicious Activity</h3>
      <p style={styles.section}>
        Any suspected fraudulent or illegal activity to win the game, such as using third-party applications or hacking, will result in the immediate termination of the User’s account.
      </p>
      <h3 style={styles.subSubHeader}>Intentionally Losing</h3>
      <p style={styles.section}>
        Any user engaging in, participating in, assisting or displaying a behavior to intentionally lose a game or match, will be considered an unfair method of participation and will result in the immediate termination of PRO GO Fantasy services for the User.
      </p>
      <h3 style={styles.subSubHeader}>Add Amount - Suspicious Activity</h3>
      <p style={styles.section}>
        Users can make transactions using multiple methods like UPI, Net banking and digital banking services.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy reserves the right to ask the user to verify the added amount in case of suspicious activity or unverified statements.
      </p>
      <p style={styles.section}>
        In case of any suspicious activity or unverified/manipulated statements, PRO GO Fantasy holds the authority to suspend the user’s account immediately.
      </p>

      <h2 style={styles.subHeader}>13. Publicity</h2>
      <p style={styles.section}>
        The winner of the Contest/(s) grants PRO GO Fantasy and its affiliates the right to use their name, likeness, voice and comments for advertising, promotion and any other media purposes worldwide, without additional compensation or consent.
      </p>
      <p style={styles.section}>
        The winner consents to be available for promotional events as determined by PRO GO Fantasy without charge.
      </p>
      <p style={styles.section}>
        The types of promotional events may include but are not limited to, press events, internal meetings, and ceremonies/functions.
      </p>

      <h2 style={styles.subHeader}>14. Level-Up Policy</h2>
      <p style={styles.section}>
        To participate in the PRO GO Fantasy Levels Program, you must be a registered User aged 18 years or older, with a valid account on the platform.
      </p>
      <p style={styles.section}>
        <strong>Level Progression:</strong> To advance through the levels, follow these steps:
        <ul style={styles.list}>
          <li>Register on PRO GO Fantasy</li>
          <li>Create your fantasy team</li>
          <li>Join your first cash contest</li>
        </ul>
      </p>
      <p style={styles.section}>
        Starting from Level 3, you need to fulfill both:
        <ul style={styles.list}>
          <li>The required number of cash contest entries</li>
          <li>The minimum total contest participation</li>
        </ul>
      </p>
      <p style={styles.section}>
        Specific levels offer additional rewards:
        <ul style={styles.list}>
          <li>Level 5: Play 2 Skill-Based Games for a ₹5 Credit Bonus</li>
          <li>Level 10: Complete your verification process for an extra ₹5</li>
          <li>Level 15: Play 5 Skill-Based Games for a ₹10 Credit Bonus</li>
          <li>Level 20: Successfully refer a friend on PRO GO Fantasy for an extra ₹10</li>
          <li>Level 25: Play 10 Skill-Based Games for a ₹15 Credit Bonus</li>
          <li>Level 35: Play 20 Skill-Based Games for a ₹20 Credit Bonus</li>
          <li>Level 45: Play 50 Skill-Based Games for a ₹25 Credit Bonus</li>
          <li>Level 50: Play Rummy contests worth ₹100 for an extra ₹30</li>
        </ul>
      </p>
      <p style={styles.section}>
        *For more information on rewards, refer to the provided table.*
      </p>
      <p style={styles.section}>
        Credit bonuses are awarded at every 5th level. The bonus amount and conditions may vary, as specified on your Level Profile Page.
      </p>
      <p style={styles.section}>
        Access your Level Profile Page from the side menu by clicking your profile name. This page displays your current level, career stats, next-level requirements, playing history, and available rewards and cash bonuses.
      </p>
      <p style={styles.section}>
        Deposits to your PRO GO Fantasy account don’t contribute to leveling up. You must use the deposited amount to join cash contests and participate in more matches to progress.
      </p>
      <p style={styles.section}>
        Only amounts from the “Unutilized” or “Your Winnings” balance count towards leveling up; cash bonuses used for contest entries don’t.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy retains the right to modify, suspend, or terminate the Program, its rules and rewards, or any user’s participation in the Program at any time, without prior notice.
      </p>

      <h2 style={styles.subHeader}>15. General Conditions</h2>
      <p style={styles.section}>
        PRO GO Fantasy reserves the right to cancel or withdraw any Contest/(s) if it is deemed necessary for compliance with any governmental, statutory, or regulatory requirements or if it breaches legal guidelines.
      </p>
      <p style={styles.section}>
        Participants agree not to make claims regarding such cancellations or withdrawals.
      </p>
      <p style={styles.section}>
        Employees, directors, affiliates, relatives, and family members of PRO GO Fantasy are not eligible to participate in any Contest(s).
      </p>
      <p style={styles.section}>
        The User’s PRO GO Fantasy Wallet balance, including winnings and the amount added, will expire if not used within 365 days. PRO GO Fantasy will make multiple attempts to remind the user of the impending expiry date through various communication modes such as SMS, email, and in-app notifications. To avoid expiration, the user must either play cash contests with the balance from their winnings or added amounts or withdraw the balance to the bank account added on PRO GO Fantasy (before the 365-day deadline).
      </p>
      <p style={styles.section}>
        If the user’s bank account details are unavailable, PRO GO Fantasy will require the user to provide the necessary information to process the withdrawal. Failure to submit bank account details within the given time frame will result in PRO GO Fantasy forfeiting the amount in the User’s PRO GO Fantasy wallet or handling it as deemed appropriate.
      </p>
      <p style={styles.section}>
        If a user decides to withdraw any amount from their PRO GO Fantasy wallet beyond the 365 days deadline, they will be subject to a processing fee. This fee will either be 5% of the total withdrawal amount or ₹10, whichever value is greater.
      </p>
      <p style={styles.section}>
        If the user does not use their PRO GO Fantasy Wallet balance for over 365 days, PRO GO Fantasy has the right to forfeit the balance without any obligation to compensate or refund the user.
      </p>

      <h2 style={styles.subHeader}>16. Dispute and Dispute Resolution</h2>
      <p style={styles.section}>
        Any disputes related to features or services provided by PRO GO Fantasy, including the Contest(s) and the interpretation and enforceability of these Terms and Conditions, shall be addressed by the competent jurisdiction of courts in Gurugram, India. All sorts of disputes, issues and questions shall be addressed by the court’s competent jurisdiction in alignment with the laws of the Republic of India.
      </p>
      <p style={styles.section}>
        In the event of a legal dispute between the parties, the party raising the dispute must provide written notification (“Notification”) to the other party. The parties should first attempt to resolve the dispute through mutual discussion within 15 days of receiving the Notification. If this fails, the dispute shall be resolved by arbitration.
      </p>
      <p style={styles.section}>
        The place of arbitration shall be in Gurugram, India and shall be conducted in English under the provisions of the Arbitration and Conciliation Act, 1996, as amended.
      </p>
      <p style={styles.section}>
        During the arbitration process, the parties shall comply with the arbitral award and bear the costs of arbitration, including the fees of the arbitrator, on their own unless otherwise stated by the arbitral tribunal.
      </p>
      <p style={styles.section}>
        The arbitrator may pass interim orders and awards, including specific performance, and these shall be enforceable in competent courts. The arbitrator is bound to provide a rational award.
      </p>

      <h2 style={styles.subHeader}>17. Grievance Redressal Mechanism</h2>
      <p style={styles.section}>
        For complaints or grievances related to:
        <ul style={styles.list}>
          <li>User content believed to violate T&Cs specified by PRO GO Fantasy (excluding Intellectual Property Rights infringement);</li>
          <li>User’s access to the PRO GO Fantasy platform;</li>
          <li>User content believed to be obscene or defamatory to the complainant or any other person on behalf of whom the complaint is made;</li>
        </ul>
        Write to: info@progofantasy.shop
      </p>
      <p style={styles.section}>
        For a complaint to be considered appropriate for action, it must include:
        <ul style={styles.list}>
          <li>Name and contact details (address, contact number, email address) of the complainant;</li>
          <li>Relation with the complainant or individual on behalf of whom the complaint is made;</li>
          <li>If acting on behalf of a person affected by the subject matter of the complaint, name and age of the affected person with a statement under perjury that the complainant is authorized to act on behalf of such individual;</li>
          <li>Clear identification of the area of complaint and description of content violations;</li>
          <li>A statement that the information provided in the complaint is verified and accurate.</li>
        </ul>
      </p>
      <p style={styles.section}>
        To file a complaint related to Intellectual Property Rights infringement, send a written notice to: info@progofantasy.shop. The complaint must include:
        <ul style={styles.list}>
          <li>Identification of the copyrighted work believed to be infringed;</li>
          <li>Identification of the infringing material;</li>
          <li>Name and contact details (address, contact number, email address) of the complainant;</li>
          <li>Statement from the complainant’s agent or law that the use of allegedly infringed copyrighted material is not authorized;</li>
          <li>A statement that the information provided in the complaint is verified and accurate;</li>
          <li>A statement under perjury that the complainant is authorized to act on behalf of the owner of the allegedly infringed copyrighted material;</li>
          <li>Signature of the complainant or authorized agent.</li>
        </ul>
      </p>
      <p style={styles.section}>
        PRO GO Fantasy reserves the right to investigate and take action as deemed appropriate against such a complaint. By accepting the T&Cs, the complainant acknowledges being available for clarification and assistance with the investigation or verification of claims made in the complaint.
      </p>
      <p style={styles.section}>
        Grievance Redressal Officer:
        <br />Name: AYUSH JAIN
        <br />Email: info@progofantasy.shop
        <br />Address: PRO GO Fantasy Sports Pvt. Ltd., Accelerator Coworking Space, Ground Floor, MGF Metropolis Mall, Mehrauli-Gurgaon Rd, Gurugram, Haryana 122002
      </p>
      <p style={styles.section}>
        The Grievance Officer is identified under the provisions of applicable laws including but not limited to the Information Technology Act, 2000 and the Consumer Protection Act, 2019 and the Rules enacted under those laws.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy reserves the right to replace the Grievance Officer, publishing the name and title of such replacement on the website, effective immediately upon publication.
      </p>

      <h2 style={styles.subHeader}>18. Release and Limitations of Liability</h2>
      <p style={styles.section}>
        The User agrees to access and use the features provided by PRO GO Fantasy voluntarily and at their sole risk and not to hold PRO GO Fantasy responsible or liable for any loss or damage sustained as a result of their access to the features, including participation in the Contest(s) or acceptance of any winnings.
      </p>
      <p style={styles.section}>
        The User is responsible for reimbursing PRO GO Fantasy and its directors, employees, partners, associates and licensors from and against any responsibility, liability, cost, loss, or expense due to their access to the features, including personal injury and damage to property.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy shall not be held responsible for any errors or omissions concerning the winnings.
      </p>
      <p style={styles.section}>
        The User accepts full responsibility for any consequences arising from any illegal activities carried out as a result of non-conformity with these Terms and Conditions and other rules and regulations regarding the features, including the provision of an incorrect address or other personal details.
      </p>
      <p style={styles.section}>
        The user consents to defend and hold PRO GO Fantasy harmless from any third-party claims arising from their involvement with www.progofantasy.shop or participation in any Contest(s) organized on the PRO GO Fantasy application.
      </p>
      <p style={styles.section}>
        The User agrees that PRO GO Fantasy shall not be held responsible for any injuries, accidents or mishaps faced due to the features or associated with the Contest(s) or the winnings of the Contests and waives and releases all rights or claims and actions against PRO GO Fantasy.
      </p>

      <h2 style={styles.subHeader}>19. Disclaimers</h2>
      <p style={styles.section}>
        Under applicable laws, PRO GO Fantasy, its parent/holding company, subsidiaries, affiliates, directors, officers, professional advisors or employees shall not be held liable for any loss, misdelivery, untimely delivery or failure to store any information or material.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy shall not be responsible for any harm caused as a result of downloading or accessing any information or material, including but not limited to games, products, features, servers, sites, cancellation of competitions and winnings. PRO GO Fantasy shall not be responsible for any inaccessibility of the features caused by maintenance on the servers, technology failures, failures of service providers, computer viruses, natural disasters, war, civil disturbance or any other cause beyond its reasonable control. Furthermore, PRO GO Fantasy does not offer any warranty for the content provided on www.progofantasy.shop or PRO GO Fantasy application.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy disclaims any responsibility for the accuracy, content, completeness, legality or reliability of information provided by third parties.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy, in addition to the above, is not responsible for any injury or damage caused by the User’s use of the website or the application.
      </p>
      <p style={styles.section}>
        The User acknowledges that they are voluntarily accessing the features provided by PRO GO Fantasy and therefore, the User accepts to bear all responsibility for the associated risks.
      </p>
      <p style={styles.section}>
        PRO GO Fantasy does not accept any liability for any losses, injuries or accidents sustained by the User or any person accompanying the User as a result of the User’s participation in the Contest(s) or use of the features.
      </p>
      <p style={styles.section}>
        To the extent permitted by law, neither PRO GO Fantasy nor any of its affiliates, directors, employees, or agents shall be liable to the User for any direct, indirect, incidental, special or consequential damages resulting from the use or inability to use the features.
      </p>
      <p style={styles.section}>
        The User accepts and agrees that the User’s sole and exclusive remedy for any dispute with PRO GO Fantasy is to discontinue using the features. The User releases PRO GO Fantasy and its directors, employees, partners, associates and licensors from any responsibility or liability concerning any loss or damage sustained by the User as a result of using the features.
      </p>
    </div>
    </div>
  );
};

const styles = {
  container: {
    padding: '20px',
    fontFamily: 'Arial, sans-serif',
    color: '#333',
    lineHeight: '1.6',
  },
  card: {
    maxWidth: '75%',
    margin: '20px auto',
    padding: '20px',
    borderRadius: '10px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
    backgroundColor: '#fff',
    fontFamily: 'Arial, sans-serif',
    color: '#333',
    lineHeight: '1.6',
  },
  image: {
    width: '75%',  // Adjust this to fit your layout
    height: '50%', // Maintain aspect ratio
    marginBottom: '20px', // Space between the image and text
  },
  header: {
    textAlign: 'center',
    color: '#004c91',
    marginBottom: '20px',
  },
  intro: {
    marginBottom: '20px',
  },
  section: {
    marginBottom: '20px',
  },
  subHeader: {
    marginTop: '30px',
    marginBottom: '10px',
    color: '#004c91',
  },
  subSubHeader: {
    marginTop: '20px',
    marginBottom: '10px',
    color: '#006699',
  },
  list: {
    listStyleType: 'disc',
    paddingLeft: '20px',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    marginBottom: '20px',
  },
  tableHeader: {
    backgroundColor: '#f4f4f4',
    fontWeight: 'bold',
  },
  tableRow: {
    borderBottom: '1px solid #ccc',
  },
  tableCell: {
    padding: '10px',
    textAlign: 'left',
  }
};

export default TermsAndConditions;
